# Generated by Django 2.2.4 on 2020-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDetails',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('contact', models.IntegerField(unique=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='provider_photo')),
            ],
        ),
    ]
