# Generated by Django 2.2.4 on 2020-08-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200812_1945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumer_details',
            new_name='ConsumerDetails',
        ),
    ]
