# Generated by Django 2.2.4 on 2020-08-12 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200812_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsumerDetails',
            new_name='Consumer_details',
        ),
    ]
