# Generated by Django 2.2.4 on 2020-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200812_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.RemoveField(
            model_name='consumerdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='consumerdetails',
            name='con_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
    ]
