# Generated by Django 2.2.4 on 2020-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200812_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('service_type', models.CharField(max_length=20)),
                ('rooms', models.IntegerField()),
                ('square_feets', models.IntegerField()),
                ('price', models.FloatField()),
                ('city', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('door_no', models.CharField(max_length=15, unique=True)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
